### ISSUE TITLE
West Barnstable Elem Walksheds Not Displaying

### ISSUE THREAD

**Issue by mzagaja** [MAPC/myschoolcommute2#126]
As a work around for #124 I manually re-ran walkshed generation for West Barnstable Elem in the rails console on my local machine. While it appears to have succeeded in creating walksheds, it fails to display anything besides the walkshed_05, which as a walkshed also looks a bit close to the school and may be incorrect.

**Comment by TimReardon** [comment]
@mzagaja this can happen when the school doesn't connect to the full street network.  I remember a case where there was a small segment of roadway within the school grounds, disconnected from the rest of the roadway network. We fixed it by moving the school point slightly so that it would connect with the full roadway network and not the fragment.

**Comment by mzagaja** [comment]
That was worth a shot. I tried moving the point out of its current walkshed and into a new one, and am still getting only walkshed_05. It turns out that when you generate the walkshed in the rails application it is generating the same walkshed for 05, 10, 15, and 20.

**Comment by bradbarnett** [comment]
@mzagaja  - Alicia asked me to take a look. It looked odd to me that the code has the value '100' as the argument for each ST_Buffer. That value sets the buffer radius, so that would explain a consistent result. Also, what are you using the "cost" variable for?

**Comment by allthesignals** [comment]
@bradbarnett that walkshed generation query was developed by consultants a few years ago so I'm not sure we would've known any of the reasoning behind it, but I will say I think cost here is aliased from the "miles" column. To see how cost is used in the context of pgrouting, see this documentation: http://docs.pgrouting.org/2.0/en/src/driving_distance/doc/dd_driving_distance.html.

**Comment by arouault** [comment]
also: this issue has only been happening for West Barnstable Elementary. I'd suggest looking at other "new" schools to see if this is an anomaly?

**Comment by allthesignals** [comment]
@arouault which schools are those?

**Comment by arouault** [comment]
A different new school would be "West Villages Elementary School"

**Comment by arouault** [comment]
@allthesignals update: I can't reproduce the error outside of West Barnstable.

**Comment by arouault** [comment]
**Working hypothesis from MAPC** The weird walkshed is actually accurate because there are no sidewalks on Main Street in West Barnstable, and therefore, no way to walk to school.

**Comment by mzagaja** [comment]
We tested with another school and the walksheds generated for it without issue.

**Comment by arouault** [comment]
Issue is closed! West Barnstable has no walk network, due to no sidewalks in MassDOT data. The walkshed is accurate.
